GroupProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', include('carviewer.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carviewer/urls.py
from django.conf.urls import url
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'carviewer'

urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),

    path('signup/', views.signup, name='signup'),

    path('carbrand_list', views.carbrand_list, name='carbrand_list'),

    path('cartype_list', views.cartype_list, name='cartype_list'),

    path('carmodel_list', views.carmodel_list, name='carmodel_list'),

    path('carreview_list', views.carreview_list, name='carreview_list'),
    path('carreview/create/', views.carreview_new, name='carreview_new'),
    path('carreview/<int:pk>/edit/', views.carreview_edit, name='carreview_edit'),
    path('carreview/<int:pk>/delete/', views.carreview_delete, name='carreview_delete'),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
         name='password_reset_done'),
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password_reset_complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
         name='password_reset_complete'),

]

carviewer/models.py
from django.db import models
from django.utils import timezone


# Define the model for the CarViewer table


class CarBrand(models.Model):
    car_brand = models.CharField(max_length=50)
    car_year = models.CharField(max_length=50)
    car_image = models.ImageField(upload_to='cars/%Y/%M/%D', blank=True)

    def __str__(self):
        return self.car_brand


class CarType(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE, related_name='cartypes', default=True)
    car_image = models.ImageField(upload_to='cars/%Y/%M/%D', blank=True)
    car_bodytype = models.CharField(max_length=50)
    car_fueltype = models.CharField(max_length=50)
    car_transmission = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    available = models.BooleanField(default=True)

    def __str__(self):
        return str(self.car_brand)


class CarModel(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE, related_name='carmodels', default=True)
    car_year = models.CharField(max_length=50)
    model_name = models.CharField(max_length=50)
    car_image = models.ImageField(upload_to='cars/%Y/%M/%D', blank=True)
    car_bodytype = models.CharField(max_length=50)
    car_fueltype = models.CharField(max_length=50)
    car_transmission = models.CharField(max_length=50)
    car_price = models.DecimalField(max_digits=10, decimal_places=2)
    car_mileage = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return str(self.car_brand)


class CarReview(models.Model):
    car_brand = models.ForeignKey(CarBrand, on_delete=models.CASCADE, related_name='carreviews', default=True)
    car_year = models.CharField(max_length=50)
    model_name = models.CharField(max_length=50)
    car_image = models.ImageField(upload_to='cars/%Y/%M/%D', blank=True)
    car_bodytype = models.CharField(max_length=50)
    car_expert_review = models.CharField(max_length=100)
    car_user_review = models.CharField(max_length=100)
    car_overall_review = models.CharField(max_length=100)

    def __str__(self):
        return str(self.car_brand)

carviewer/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import CarBrand, CarType, CarModel, CarReview


class CarBrandForm(forms.ModelForm):
    class Meta:
        model = CarBrand
        fields = ('car_brand', 'car_year', 'car_image')


class CarTypeForm(forms.ModelForm):
    class Meta:
        model = CarType
        fields = ('car_brand', 'car_image', 'car_bodytype', 'car_fueltype', 'car_transmission', 'description', 'available')


class CarModelForm(forms.ModelForm):
    class Meta:
        model = CarModel
        fields = (
            'car_brand', 'car_year', 'model_name', 'car_image',  'car_bodytype', 'car_fueltype', 'car_transmission', 'car_price',
            'car_mileage')


class CarReviewForm(forms.ModelForm):
    class Meta:
        model = CarReview
        fields = ('car_brand', 'car_year', 'model_name', 'car_image', 'car_bodytype', 'car_expert_review', 'car_user_review',
                  'car_overall_review')


class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


def __init__(self, *args, **kwargs):
    super(CustomUserCreationForm, self).__init__(*args, **kwargs)

    for name, field in self.fields.items():
        field.widget.attrs.update({'class': 'form-control'})

carviewer/views.py
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import *
from .forms import *
from .forms import CustomUserCreationForm

now = timezone.now()
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


# HomePage
def home(request):
    return render(request, 'carviewer/home.html',
                  {'carviewer': home})


# CarBrand
@login_required
def carbrand_list(request):
    carbrand = CarBrand.objects.filter()
    return render(request, 'carviewer/carbrand_list.html',
                  {'carbrands': carbrand})


# CarType
@login_required
def cartype_list(request):
    cartype = CarType.objects.filter()
    return render(request, 'carviewer/cartype_list.html',
                  {'cartypes': cartype})


# CarModel
@login_required
def carmodel_list(request):
    carmodel = CarModel.objects.filter()
    return render(request, 'carviewer/carmodel_list.html',
                  {'carmodels': carmodel})


# CarReview
@login_required
def carreview_list(request):
    carreview = CarReview.objects.filter()
    return render(request, 'carviewer/carreview_list.html',
                  {'carreviews': carreview})


@login_required
def carreview_new(request):
    if request.method == "POST":
        form = CarReviewForm(request.POST)
        if form.is_valid():
            carreview = form.save(commit=False)
            carreview.created_date = timezone.now()
            carreview.save()
            carreview = CarReview.objects.filter()
            return render(request, 'carviewer/carreview_list.html',
                          {'carreviews': carreview})
    else:
        form = CarReviewForm()

    return render(request, 'carviewer/carreview_new.html', {'form': form})


@login_required
def carreview_edit(request, pk):
    carreview = get_object_or_404(CarReview, pk=pk)
    if request.method == "POST":
        form = CarReviewForm(request.POST, instance=carreview)
        if form.is_valid():
            carreview = form.save()
            carreview.updated_date = timezone.now()
            carreview.save()
            carreview = CarReview.objects.filter()
            return render(request, 'carviewer/carreview_list.html', {'carreviews': carreview})
    else:
        form = CarReviewForm(instance=carreview)
    return render(request, 'carviewer/carreview_edit.html', {'form': form})


@login_required
def carreview_delete(request, pk):
    carreview = get_object_or_404(CarReview, pk=pk)
    carreview.delete()
    return redirect('carviewer:carreview_list')


def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)

            return redirect('login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

carviewer/templates/carviewer/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
<title>CarViewer</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
div.gallery {
  border: 1px solid #ccc;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height: auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
/*This is for search box*/
.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav input[type=text] {
  float: right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 16px;
  border: none;
  font-size: 17px;
}
@media screen and (max-width: 600px) {
  .topnav a, .topnav input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }

  .topnav input[type=text] {
    border: 1px solid #ccc;
  }
}
/* Style the header this is about us box */
header {
  background-color: #666;
  width: 100%;
  height: 300px;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

/* Create two columns/boxes that floats next to each other box on right side */
nav {
  float: left;
  width: 10%;
  height: 600px; /* only for demonstration, should be removed */
  background: #ccc;
  padding: 5px;
}

/* Style the list inside the menu */
nav ul {
  list-style-type: none;
  padding: 0;
}

article {
  float: right;
  padding: 10px;
  width: 90%;
  background-color: #f1f1f1;
  height: 600px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section::after {
  content: "";
  text-align: center;
  display: table;
  clear: both;
}

/* Style the footer */
footer {
  background-color: #777;
  padding: 5px;
  text-align: center;
  color: white;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}
/*this is for responsive image gallery*/
.responsive {
  padding: 0 6px;
  float: left;
  width: 24.99999%;
}

@media only screen and (max-width: 700px) {
  .responsive {
    width: 49.99999%;
    margin: 6px 0;
  }
}

@media only screen and (max-width: 500px) {
  .responsive {
    width: 100%;
  }
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>
<body>

<h1 style="font-family:'Marker Felt', fantasy">CarViewer</h1>


<div class="topnav">
  <a href="{% url 'carviewer:home' %}">Home</a>
  <a href="{% url 'carviewer:carbrand_list' %}">Car Brands</a>
  <a href="{% url 'carviewer:carmodel_list' %}">Car Models</a>
  <a href="{% url 'carviewer:cartype_list' %}">Car Types</a>
  <input type="text" placeholder="Search..">

            {% if user.is_authenticated %}
                <a style="font-family:'Stencil Std', fantasy">Welcome, {{ user.username }}</a>
                <a class="topnav" href="{% url 'carviewer:logout' %}">Logout</a>
            {% else %}

                <a class="topnav" href="{% url 'carviewer:login' %}">Login</a>

                <a class="topnav" href="{% url 'carviewer:signup' %}">Signup</a>

            {% endif %}
    </div>


</div>
<body id="app-layout">
<div class="row">
    <div class="col-md-8">
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }} ">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% block content %}
        {% endblock %}
    </div>
</div>
</div>
</div>
</body>
</body>
</html>

carviewer/templates/carviewer/carbrand_list.html
<!DOCTYPE html>
<html lang="en">

{% extends 'carviewer/base.html' %}
{% load static %}
{% block content %}


    <html>
    <head>
<title>CarViewer</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
div.gallery {
  border: 1px solid #ccc;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height:auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
/*This is for search box*/
.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav input[type=text] {
  float: right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 16px;
  border: none;
  font-size: 17px;
}
@media screen and (max-width: 600px) {
  .topnav a, .topnav input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }

  .topnav input[type=text] {
    border: 1px solid #ccc;
  }
}
/* Style the header this is about us box */
header {
  background-color: #666;
  width: 100%;
  height: 300px;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

/* Create two columns/boxes that floats next to each other box on right side */
nav {
  float: left;
  width: 10%;
  height: 600px; /* only for demonstration, should be removed */
  background: #ccc;
  padding: 5px;
}

/* Style the list inside the menu */
nav ul {
  list-style-type: none;
  padding: 0;
}

article {
  float: right;
  padding: 10px;
  width: 90%;
  background-color: #f1f1f1;
  height: 600px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section::after {
  content: "";
  text-align: center;
  display: table;
  clear: both;
}

/* Style the footer */
footer {
  background-color: #777;
  padding: 5px;
  text-align: center;
  color: white;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}
/*this is for responsive image gallery*/
.responsive {
  padding: 0 6px;
  float: left;
  width: 24.99999%;
}

@media only screen and (max-width: 700px) {
  .responsive {
    width: 49.99999%;
    margin: 6px 0;
  }
}

@media only screen and (max-width: 500px) {
  .responsive {
    width: 100%;
  }
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>


    <body>

 <section>
  <nav>
    <h4 style="font-family:'Comic Sans MS', 'Comic Sans', cursive"> Navigate </h4>
    <ul>

      <img src="/static/Images/Brands.png" alt="Sample" width="80" height="60">
<li><a href="{% url 'carviewer:carbrand_list' %}">Car Brands</a></li>
<br>
<br>

      <img src="/static/Images/Model.png" alt="Sample1" width="80" height="60">
<li><a href="{% url 'carviewer:carmodel_list' %}">Car Models</a></li>

<br>
<br>

      <img src="/static/Images/Types.png" alt="Sample2" width="80" height="60">
<li><a href="{% url 'carviewer:cartype_list' %}">Car Types</a></li>
<br>
<br>


      <img src="/static/Images/Reviews.png" alt="Sample3" width="80" height="60">
<li><a href="{% url 'carviewer:carreview_list' %}">Car Reviews</a></li>
    </ul>
  </nav>


 <article>

        <h1 style="font-family:'Comic Sans MS', 'Comic Sans', cursive" >Our Brands</h1>

    <!--    <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Car Brand Name</th>
                <th>Car Year</th>
                <th>Car Image</th>

            </tr>
            </thead>
            <tbody>   -->


     {% for carbrand in carbrands %}
                <tr>

<div class="responsive">
<div class="gallery">
     <td>
        <a target="_blank" href="">
         <img src="{% if carbrand.car_image %}{{ carbrand.car_image.url }}{% else %}{% static "images/Reviews.png" %}{% endif %}" alt="Brand Name" width="600" height="400">
        </a>
         {{ carbrand.car_brand }} in {{ carbrand.car_year }}
     </td>

</div>
</div>
     </tr>
{% endfor %}

     </tbody>
        </table>

   </article>
</section>


</body>

{% endblock %}
</html>

carviewer/templates/carviewer/carreview_delete.html
<!DOCTYPE html>
<html lang="en">
{% block body_block %}
    <h1>Delete {{ carreview.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'carviewer:home' pk=carreview.carreview_number %} ">Cancel</a>
    </form>
{% endblock %}

</html>

carviewer/templates/carviewer/carreview_edit.html
<!DOCTYPE html>
<html lang="en">
{% extends 'carviewer/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <style> body { background-color: beige; } </style>
    <h1>Edit CarReviews</h1>
    <form method="POST" class="carreview-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Update</button>
    </form>
{% endblock %}
</html>

carviewer/templates/carviewer/carreview_list.html
<!DOCTYPE html>
<html lang="en">
{% extends 'carviewer/base.html' %}
{% load static %}
{% block content %}

    <html>
    <head>
<title>CarViewer</title>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
div.gallery {
  border: 1px solid #ccc;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height: auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

* {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}
/*This is for search box*/
.topnav {
  overflow: hidden;
  background-color: #e9e9e9;
}

.topnav a {
  float: left;
  display: block;
  color: black;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #2196F3;
  color: white;
}

.topnav input[type=text] {
  float: right;
  padding: 6px;
  margin-top: 8px;
  margin-right: 16px;
  border: none;
  font-size: 17px;
}
@media screen and (max-width: 600px) {
  .topnav a, .topnav input[type=text] {
    float: none;
    display: block;
    text-align: left;
    width: 100%;
    margin: 0;
    padding: 14px;
  }

  .topnav input[type=text] {
    border: 1px solid #ccc;
  }
}
/* Style the header this is about us box */
header {
  background-color: #666;
  width: 100%;
  height: 300px;
  padding: 30px;
  text-align: center;
  font-size: 35px;
  color: white;
}

/* Create two columns/boxes that floats next to each other box on right side */
nav {
  float: left;
  width: 10%;
  height: 600px; /* only for demonstration, should be removed */
  background: #ccc;
  padding: 5px;
}

/* Style the list inside the menu */
nav ul {
  list-style-type: none;
  padding: 0;
}

article {
  float: right;
  padding: 10px;
  width: 90%;
  background-color: #f1f1f1;
  height: 600px; /* only for demonstration, should be removed */
}

/* Clear floats after the columns */
section::after {
  content: "";
  text-align: center;
  display: table;
  clear: both;
}

/* Style the footer */
footer {
  background-color: #777;
  padding: 5px;
  text-align: center;
  color: white;
}

/* Responsive layout - makes the two columns/boxes stack on top of each other instead of next to each other, on small screens */
@media (max-width: 600px) {
  nav, article {
    width: 100%;
    height: auto;
  }
}
/*this is for responsive image gallery*/
.responsive {
  padding: 0 6px;
  float: left;
  width: 24.99999%;
}

@media only screen and (max-width: 700px) {
  .responsive {
    width: 49.99999%;
    margin: 6px 0;
  }
}

@media only screen and (max-width: 500px) {
  .responsive {
    width: 100%;
  }
}

.clearfix:after {
  content: "";
  display: table;
  clear: both;
}
</style>
</head>


 <body>

    <section>
  <nav>
    <h4 style="font-family:'Comic Sans MS', 'Comic Sans', cursive"> Navigate </h4>
    <ul>

      <img src="/static/Images/Brands.png" alt="Sample" width="80" height="60">
<li><a href="{% url 'carviewer:carbrand_list' %}">Car Brands</a></li>
<br>
<br>

      <img src="/static/Images/Model.png" alt="Sample1" width="80" height="60">
<li><a href="{% url 'carviewer:carmodel_list' %}">Car Models</a></li>

<br>
<br>

      <img src="/static/Images/Types.png" alt="Sample2" width="80" height="60">
<li><a href="{% url 'carviewer:cartype_list' %}">Car Types</a></li>
<br>
<br>


      <img src="/static/Images/Reviews.png" alt="Sample3" width="80" height="60">
<li><a href="{% url 'carviewer:carreview_list' %}">Car Reviews</a></li>
    </ul>
  </nav>


   <article>

        <h1 style="font-family:'Comic Sans MS', 'Comic Sans', cursive" >Our Reviews</h1>

   <!--     <table class="table table-striped table-bordered table-hover w-auto">
            <thead>
            <tr class="bg-info">
                <th>Car Brand Name</th>
                <th>Model Name</th>
                <th>Car Year</th>
                <th>Car Image</th>
                <th>Car BodyType</th>
                <th>Car Expert Review</th>
                <th>Car User Review</th>
                <th>Car Overall Review</th>

                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>  -->

            {% for carreview in carreviews %}

                 <div class="responsive">
                <div class="gallery">
                <a target="_blank" href="">
                <img src="{% if carreview.car_image %}{{ carreview.car_image.url }}{% else %}{% static "images/Reviews.png" %}{% endif %}" alt="New Image">
                </a>
                    <td>{{ carreview.car_brand }}</td>
                <br>
                    <td>{{ carreview.car_year }}</td>
                <br>
                    <td>{{ carreview.model_name }}</td>
                <br>
                    <td>{{ carreview.car_bodytype }}</td>
                <br>
                    <td>{{ carreview.car_expert_review }}</td>
                <br>
                    <td>{{ carreview.car_user_review }}</td>
                <br>
                    <td>{{ carreview.car_overall_review }}</td>

                    <td><a href="{% url 'carviewer:carreview_edit' pk=carreview.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'carviewer:carreview_delete' pk=carreview.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>



               </div>
</div>
     </tr>
{% endfor %}

     </tbody>
        </table>

   </article>
</section>


</body>

{% endblock %}
</html>

carviewer/templates/carviewer/carreview_new.html
<!DOCTYPE html>
<html lang="en">
{% extends 'carviewer/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New CarReview</h1>
    <form method="POST" class="carreview-form">{% csrf_token %}
         {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
{% endblock %}
</html>